-- =============================================================================
-- Migration 003: idempotency key for offline-synced bills
--
-- client_bill_id is a UUID generated by the Flutter client before the bill is
-- queued offline.  It is sent in every POST /api/bills request so the server
-- can detect duplicate submissions (e.g. network timeout + retry) and return
-- the already-created bill instead of inserting a second row.
--
-- Design:
--   • NULLable — bills created directly online (not via the offline queue)
--     have no client_bill_id and are never subject to deduplication.
--   • Partial unique index on (business_id, client_bill_id) WHERE
--     client_bill_id IS NOT NULL — enforces uniqueness only for offline bills.
-- =============================================================================

IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('bills')
      AND name = 'client_bill_id'
)
BEGIN
    ALTER TABLE bills
        ADD client_bill_id NVARCHAR(36) NULL
END
GO

-- Partial unique index: one client_bill_id per business, NULLs excluded.
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UQ_bills_client_bill_id'
      AND object_id = OBJECT_ID('bills')
)
BEGIN
    CREATE UNIQUE INDEX UQ_bills_client_bill_id
        ON bills (business_id, client_bill_id)
        WHERE client_bill_id IS NOT NULL
END
GO
