// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnqzxrqewW1NPxx2yW63oTa2oJ4uIG5VI',
    appId: '1:231979154689:web:f3b2c3f9e9fcc945fdaf00',
    messagingSenderId: '231979154689',
    projectId: 'vittam-ffc4c',
    authDomain: 'vittam-ffc4c.firebaseapp.com',
    storageBucket: 'vittam-ffc4c.firebasestorage.app',
    measurementId: 'G-GHHYT6SRR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABWkcN-CnKwVSPN7roZMhcIjPFVzJvgyg',
    appId: '1:231979154689:android:67c6f963324f91c0fdaf00',
    messagingSenderId: '231979154689',
    projectId: 'vittam-ffc4c',
    storageBucket: 'vittam-ffc4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn6v7DixsJXq145In6eGOWof7iXoMFM2s',
    appId: '1:231979154689:ios:69ee9641bb762cb0fdaf00',
    messagingSenderId: '231979154689',
    projectId: 'vittam-ffc4c',
    storageBucket: 'vittam-ffc4c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn6v7DixsJXq145In6eGOWof7iXoMFM2s',
    appId: '1:231979154689:ios:69ee9641bb762cb0fdaf00',
    messagingSenderId: '231979154689',
    projectId: 'vittam-ffc4c',
    storageBucket: 'vittam-ffc4c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnqzxrqewW1NPxx2yW63oTa2oJ4uIG5VI',
    appId: '1:231979154689:web:5672c992ca13fbfefdaf00',
    messagingSenderId: '231979154689',
    projectId: 'vittam-ffc4c',
    authDomain: 'vittam-ffc4c.firebaseapp.com',
    storageBucket: 'vittam-ffc4c.firebasestorage.app',
    measurementId: 'G-W5EWC9VHTG',
  );
}
